### ISSUE TITLE
MS3

### ISSUE THREAD

**Issue by CodeKittey** [Pathen85/Pathen#2]
Ihr habt zuviel Zeit, da ihr anscheinend schon den dritten Meilenstein fertig habt ;)
Aber ein paar Dinge koennt ihr trotzdem noch morgen dafuer aendern/ mitnehmen.

**Comment by Pathen85** [comment]
Wir kommen auf jeden Fall morgen :wink:

**Comment by CodeKittey** [comment]
MEINEN Issue closen, ich glaub es hackt :stuck_out_tongue_closed_eyes:

**Comment by Pathen85** [comment]
Na guuut.. :smile:

**Comment by CodeKittey** [comment]
Perfekt jetzt kann ich ihn naemlich closen :smirk: :smirk_cat:
